services:
  database:
    image: hub.docker.internal.cba/postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: luyangliuable
      POSTGRES_PASSWORD: password
      POSTGRES_DB: llcode
