sonar.projectKey=luyangliuable_personal-portfolio-next
sonar.organization=luyangliuable
sonar.host.url=https://sonarcloud.io
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.test.tsx,**/*.spec.ts,**/*.spec.tsx,**/*.config.js,**/*.config.ts,**/dist/**,**/build/**,**/.next/**
sonar.coverage.exclusions=**/*
